### ISSUE TITLE
caja-admin causes to caja-file-management-properties fill ~/.xsession-errors with python-related warnings

### ISSUE THREAD

**Issue by N0rbert** [infirit/caja-admin#15] opened 2021-09-25 18:15 UTC
Steps to reproduce:
1. Install Ubuntu MATE 21.10 beta
2. Launch `caja-file-management-properties` from terminal

Expected results: terminal shows only three lines 

```
Initializing caja-wallpaper extension
Initializing caja-sendto extension
Initializing caja-open-terminal extension
```

Actual results: terminal shows many lines like shown below

```
(caja-file-management-properties:6800): Gtk-WARNING **: 21:09:10.379: Failed to set text from markup due to error parsing markup: Error on line 1 char 26: Invalid UTF-8 encoded text in name — not valid “Python: \xcb\xe7%C\xb3U”
```

If user starts Caja and goes to Edit → Preferences and then to Extensions tab then `~/.xsession-errors` fills with above messages.

Downstream meta-bug - https://pad.lv/1945052 .

**Comment by infirit** [comment] 2021-09-25 18:19
How is this related to caja-admin?

**Comment by N0rbert** [comment] 2021-09-25 18:19
Thanks for reactive reply!

Caja-admin is python-based, has extension [in](https://packages.ubuntu.com/impish/all/caja-admin/filelist) /usr/share/caja-python/extensions/caja-admin.py . I expect that it is why.

**Comment by infirit** [comment] 2021-09-25 18:23
There is nothing in what you posted that suggests that this has anything to do with caja-admin. It may be the caja-python that is the cause of the error. Is the problem still there is you uninstall caja-admin?

edit: I also can't reproduce this locally with version 0.0.5.

**Comment by N0rbert** [comment] 2021-09-25 18:31
Uninstallation of caja-admin helps, that is true. Digging deeper now, caja-rename is affected too.
Current situation with Caja-python extensions:

```
[!!] caja-admin
[ok] caja-mediainfo
[!!] caja-rename
[!!] deja-dup-caja 
[ok] folder-color-caja
```

I do not really know the internals of these extensions, but Gtk-Warnings exist and looks as shown above.

**Comment by infirit** [comment] 2021-09-25 18:34
Then it is unlikely to be the python extension but rather python-caja. Pyhon-caja is what loads these python scripts.

**Comment by infirit** [comment] 2022-10-20 20:22
Closing as this was traced to a commit in python-caja.

**Closed as completed by infirit** 2022-10-20 20:22 UTC
Labels: question
